name: Build and Push Docker Image

on:
  workflow_call:
    secrets:
      google_gar_repo:
        required: true
      gar_json_key:
        required: true

jobs:
  build_publish_docker_image:
    name: Push Docker image to Github Container Reg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version and Lowercase Repo
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_SHA} | head -c 12)" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set current date as env variable
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.gar_json_key }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.google_gar_repo }}/${{ github.event.repository.name }}:${{GITHUB_REF_NAME}}-${{ env.RELEASE_VERSION }}-${{ env.TIMESTAMP }}
            ${{ secrets.google_gar_repo }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}
            ${{ secrets.google_gar_repo }}/${{ github.event.repository.name }}:latest