name: Build & push to gcr
on:
    workflow_call:
        inputs:
            image_name:
                required: true
                type: string
            project_id:
                required: false
                type: string
                default: "capturelab"
            registry:
                required: false
                type: string
                default: "eu.gcr.io"
        secrets:
            GCLOUD_SERVICE_KEY:
                required: true

jobs:
    build-and-push-to-gcr:
        runs-on: ubuntu-latest
        steps:
            - name: base64 encode the gcr sa
              id: base64-encode
              run: echo "::set-output name=BRANCH_BASE64::$(echo -n ${{ github.head_ref || github.ref_name }} | base64 | sed 's/=//g')"

            - uses: actions/checkout@v2
            - name: 'Build'
              uses: RafikFarhad/push-to-gcr-github-action@v5-beta
              with:
                  gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
                  registry: ${{ inputs.registry }}
                  project_id: ${{ inputs.project_id }}
                  image_name: ${{ inputs.image_name }}
                  image_tag: '${{ steps.base64-encode.outputs.BRANCH_BASE64 }}'
                  context: .
