name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
    secrets:
      google_gar_repo:
        required: true
      gar_json_key:
        required: true

jobs:
  build_publish_docker_image:
    name: Push Docker image to Github Container Reg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${{inputs.commit_sha}}" >> $GITHUB_ENV
      - name: Set Repo lowercase
        run: echo "REPO=$(echo ${{inputs.repo_name}} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.gar_json_key }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.google_gar_repo }}/${{ env.REPO }}:${{ env.RELEASE_VERSION }}
            ${{ secrets.google_gar_repo }}/${{ env.REPO }}:latest