name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      commit-sha:
        required: true
        type: string

jobs:
  build_publish_docker_image:
    name: Push Docker image to Github Container Reg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${inputs.commit-sha}" >> $GITHUB_ENV
      - name: Set Repo lowercase
        run: echo "REPO=${inputs.repo-name,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            gcr.io/${{ env.REPO }}:${{ env.RELEASE_VERSION }}
            gcr.io/${{ env.REPO }}:latest