name: Deploy to cloud run
on:
    workflow_call:
        inputs:
            meta_data:
                required: true
                type: string
        secrets:
            GCP_SA_KEY:
                required: true

jobs:
    deploy-to-cloud-run:
        permissions:
          contents: 'read'
          id-token: 'write'
        runs-on: ubuntu-latest
        steps:
          - name: 'base64 encode the gcr sa'
            id: base64-encode
            run: echo "::set-output name=BRANCH_BASE64::$(echo -n ${{ github.head_ref || github.ref_name }} | base64 | sed 's/=//g')"

          - id: 'auth'
            uses: 'google-github-actions/auth@v0.8.3'
            with:
              credentials_json: '${{ secrets.GCP_SA_KEY }}'

          - name: 'Deploy to Cloud Run'
            uses: 'google-github-actions/deploy-cloudrun@v0.10.3'
            with:
              metadata: '${{ inputs.meta_data }}'
